on:
  pull_request:
    types: [ closed ]
    branches:
    - main

jobs:
   refresh_index:
    runs-on: ubuntu-20.0.4
    permissions:
       contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.13.2'
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            import json

            def count_tags(tags, article, name):
               found = False
               for a in article["tags"]:
                 for t in tags:
                    if t["text"] == a:
                       t["value"] += 1
                       t["items"].append({"title":article["title"], "uri": name})
                       found = True
               if not found:
                  tags.append({"text":a, "value":1, "items":[{"title":article["title"], "uri": name}]})
               return tags


            template = open("index.temp")
            ret = json.loads(template.read())

            for root, dirs, files in os.walk("articles", topdown=False):
               for name in files:
                  f = open(os.path.join(root, name))
                  uri = name.split(".") # Don't want the .json part
                  data = json.load(f)
                  ret["articles"].append({"title":data["title"], "uri": uri[0]})
                  ret["tags"] = count_tags(ret["tags"], data, name)

            out = open("index.json", "w")
            out.write(json.dumps(ret))
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
           commit_message: Updating index.json
